### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by kilyman**
arm64 changes

### CODE REVIEW

**Comment by k3a** [comment]
Thanks. So the "bad rebase opcode 222" problem was caused by deployment target lower than 5.1.1?

**Comment by k3a** [comment]
Unfortunately even with your patch and deployment target I still can't load the bundle on my iPhone 4 @ 7.0.4 (so armv7). But armv7-only bundle loads just fine.

I am getting this for fat bundle:
 Preferences[2373]: Error loading /Library/PreferenceBundles/SEPrefs.bundle/SEPrefs:  dlopen(/Library/PreferenceBundles/SEPrefs.bundle/SEPrefs, 265): bad rebase opcode 222 in /Library/PreferenceBundles/SEPrefs.bundle/SEPrefs

Any idea why?

**Comment by kilyman** [comment]
I copied my compiled prefs bundle to my iPad2 it is working too.

**Comment by k3a** [comment]
Heh I am getting "bad rebase opcode 222" on my iPad2 on iOS 5.1.1. If it works on yours then it must be toolkit, headers or theos problem. Ok I will install latest theos and headers and will see...

**Comment by k3a** [comment]
Thanks again. SpeakEvents source code was updated for theos/iphoneheaders combo you mentioned (pushed to github)!

**Comment by Sohailwahab** [comment]
@k3a please fix the following issues with your tweak SpeakEvents

1_Make it pause/resume music after speaking notifications & events ( I even turned on that IN Bluetooth HF but it's not working 
2_The custom volume is not getting up, compare to device volume the speaking notification volume is much lower
3_Most of the customized announcements doesn't work
4_Causes device to safe mode while selecting clock app to speak 

These issues occurred on iPad 3 with iOS 7.1.2 & 7.0.4

**Pull request merged**
